'use strict';
const $=id=>document.getElementById(id),canvas=$('art'),ctx=canvas.getContext('2d');
const strains=[{name:'青綠螢光',sub:'虛擬菌株 A',color:'#53f5cf',day:'#a2bfb0',type:'fluor',grow:1.2,info:'需激發光才呈現鮮明螢光。模擬擴展較明顯，適合先預留空隙。'},{name:'桃紅螢光',sub:'虛擬菌株 B',color:'#ff81ba',day:'#cd6e99',type:'fluor',grow:.8,info:'需激發光才呈現鮮明螢光。模擬擴展適中，可用於輪廓與重點。'},{name:'金黃螢光',sub:'虛擬菌株 C',color:'#ffe78c',day:'#d1af58',type:'fluor',grow:1,info:'需激發光才呈現鮮明螢光。可以點畫小面積細節。'},{name:'紫色色素',sub:'虛擬菌株 D',color:'#a38ae8',day:'#825bab',type:'pigment',grow:.6,info:'紫色色素的虛擬配色，不在黑暗中發光。本練習的普通光模式統一隱藏菌株顏色。'},{name:'藍青自體發光',sub:'虛擬菌株 E',color:'#80e6ff',day:'#c7c9b0',type:'bio',grow:.9,info:'模擬自體發光機制，黑暗中可見藍青色。不是螢光。'}];
let state={strokes:[],shape:'rect',place:'',title:'',story:'',members:['','','','']},history=[],future=[],selected=0,member=0,tool='pen',light='day',growth=0,current=null,drawing=false,timer=null;
strains.forEach((s,i)=>{let b=document.createElement('button');b.className='swatch';b.style.setProperty('--color',s.color);b.innerHTML=`<i></i><span><strong>${s.name}</strong><small>${s.sub}</small></span>`;b.onclick=()=>{selected=i;refresh()};$('palette').append(b)});
for(let i=0;i<4;i++){const row=document.createElement('div');row.className='member';const b=document.createElement('button');b.textContent=i+1;b.title=`切換至組員 ${i+1}`;b.onclick=()=>{member=i;refresh()};const input=document.createElement('input');input.placeholder=`組員 ${i+1} 姓名`;input.maxLength=30;input.setAttribute('aria-label',`組員 ${i+1} 姓名`);input.oninput=()=>state.members[i]=input.value;row.append(b,input);$('members').append(row)}
function toast(t){$('toast').textContent=t;$('toast').style.display='block';clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').style.display='none',3200)}
function checkpoint(){history.push(JSON.stringify(state.strokes));if(history.length>50)history.shift();future=[]}
function refresh(){document.querySelectorAll('.swatch').forEach((b,i)=>{b.classList.toggle('active',i===selected);b.setAttribute('aria-pressed',i===selected)});$('strainInfo').textContent=strains[selected].info;document.querySelectorAll('#members button').forEach((b,i)=>b.classList.toggle('active',i===member));document.querySelectorAll('#tools button').forEach(b=>b.classList.toggle('active',b.dataset.tool===tool));document.querySelectorAll('#lights button').forEach(b=>b.classList.toggle('active',b.dataset.light===light));$('empty').style.display=state.strokes.length?'none':'flex';$('undo').disabled=!history.length;$('redo').disabled=!future.length;$('growthOut').textContent=growth===0?'落筆':growth<50?'菌落形成 '+growth+'%':'擴展 '+growth+'%';$('drawingStatus').textContent=growth?'預覽中 · 回到落筆可繪畫':`組員 ${member+1} · 落筆模式`;$('lightNote').textContent=light==='day'?'普通光練習：塗抹不顯示菌株顏色，只保留淡淡的透明濕痕；切換激發光查看配色。':light==='dark'?'黑暗示意：只有虛擬自體發光菌株 E 顯示發光。':'激發光示意：虛擬螢光菌株的顏色更鮮明。';draw()}
const quadPlates=[{x:158,y:48},{x:462,y:48},{x:158,y:352},{x:462,y:352}];
function plate(c){c.beginPath();if(state.shape==='quad'){for(const r of quadPlates)c.roundRect(r.x,r.y,280,280,24)}else if(state.shape==='circle')c.arc(450,340,295,0,Math.PI*2);else c.roundRect(60,50,780,580,38)}
function inside(p){if(state.shape==='quad')return quadPlates.some(r=>p.x>r.x+5&&p.x<r.x+275&&p.y>r.y+5&&p.y<r.y+275);return state.shape==='circle'?(p.x-450)**2+(p.y-340)**2<290**2:p.x>65&&p.x<835&&p.y>55&&p.y<625}
function draw(target=ctx){const c=target;c.clearRect(0,0,900,680);c.fillStyle=light==='day'?'#dee0d5':'#0a1a27';c.fillRect(0,0,900,680);plate(c);c.fillStyle=light==='day'?'#c9bf8b':light==='dark'?'#080f18':'#0c354d';c.fill();c.lineWidth=12;c.strokeStyle=light==='day'?'#b0b6a5':'#244f68';c.stroke();c.lineWidth=2;c.strokeStyle=light==='day'?'#f0efd8':'#6193ab';c.stroke();c.save();plate(c);c.clip();for(const stroke of [...state.strokes,...(current?[current]:[])]){const s=strains[stroke.strain];for(let i=0;i<stroke.points.length;i++){const p=stroke.points[i],seed=Math.sin(p.x*12.9898+p.y*78.233+i)*43758.5453,f=seed-Math.floor(seed),radius=stroke.size/2*(.55+f*.4)*(1+growth/100*s.grow*1.8);c.globalAlpha=light==='day'?.065:light==='dark'?(s.type==='bio'?.95:.055):s.type==='pigment'&&light==='excite'?.35:.87;c.fillStyle=light==='day'?'#ffffff':s.color;c.shadowColor=s.color;c.shadowBlur=light==='day'||s.type==='pigment'||(light==='dark'&&s.type!=='bio')?0:radius*.9;c.beginPath();c.ellipse(p.x,p.y,radius,radius*(.78+f*.22),f*3,0,Math.PI*2);c.fill();if(growth>20){c.globalAlpha*=.23;c.shadowBlur=0;c.fillStyle='#ffffff';c.beginPath();c.arc(p.x-radius*.25,p.y-radius*.25,Math.max(.6,radius*.2),0,7);c.fill()}}}c.restore();c.shadowBlur=0;c.globalAlpha=1;if(state.shape==='quad'){c.font='bold 18px sans-serif';c.fillStyle=light==='day'?'#405045':'#b0d4df';quadPlates.forEach((r,i)=>c.fillText(String(i+1),r.x-28,r.y+25))}}
function point(e){const r=canvas.getBoundingClientRect();return {x:(e.clientX-r.left)*900/r.width,y:(e.clientY-r.top)*680/r.height}}
function erase(p){state.strokes=state.strokes.map(s=>({...s,points:s.points.filter(q=>Math.hypot(p.x-q.x,p.y-q.y)>Number($('size').value)*1.5)})).filter(s=>s.points.length)}
canvas.onpointerdown=e=>{if(growth){toast('把生長滑桿拉回「落筆」，便可繼續繪畫。');return}const p=point(e);if(!inside(p))return;e.preventDefault();canvas.setPointerCapture(e.pointerId);checkpoint();drawing=true;if(tool==='erase')erase(p);else current={strain:selected,member,size:Number($('size').value),points:[p]};draw()};
canvas.onpointermove=e=>{if(!drawing)return;const p=point(e);if(!inside(p))return;if(tool==='erase')erase(p);else if(tool==='pen'){let last=current.points.at(-1),d=Math.hypot(p.x-last.x,p.y-last.y),step=Math.max(2,current.size*.35),n=Math.floor(d/step);for(let i=1;i<=n;i++)current.points.push({x:last.x+(p.x-last.x)*i/n,y:last.y+(p.y-last.y)*i/n})}draw()};
function end(){if(!drawing)return;drawing=false;if(current)state.strokes.push(current);current=null;refresh()};canvas.onpointerup=end;canvas.onpointercancel=end;canvas.onlostpointercapture=end;
$('tools').onclick=e=>{if(e.target.dataset.tool){tool=e.target.dataset.tool;refresh()}};$('lights').onclick=e=>{if(e.target.dataset.light){light=e.target.dataset.light;refresh()}};$('size').oninput=()=>{$('sizeOut').textContent=$('size').value};$('shape').onchange=()=>{state.shape=$('shape').value;refresh();toast(state.shape==='quad'?'已切換為四皿拼圖：左上 1、右上 2、左下 3、右下 4；皿外筆觸仍保留。':'形狀已切換；外圍筆觸會被遮住，但仍保留。')};
$('undo').onclick=()=>{if(history.length){future.push(JSON.stringify(state.strokes));state.strokes=JSON.parse(history.pop());refresh()}};$('redo').onclick=()=>{if(future.length){history.push(JSON.stringify(state.strokes));state.strokes=JSON.parse(future.pop());refresh()}};$('clear').onclick=()=>{if(state.strokes.length&&confirm('清空畫布？可以按「復原」還原。')){checkpoint();state.strokes=[];refresh()}};
function stop(){clearInterval(timer);timer=null;$('play').textContent='播放生長'};$('growth').oninput=()=>{stop();growth=Number($('growth').value);refresh()};$('play').onclick=()=>{if(timer){stop();return}if(growth>=100)growth=0;timer=setInterval(()=>{growth=Math.min(100,growth+1);$('growth').value=growth;refresh();if(growth===100)stop()},65);$('play').textContent='暫停'};
$('sample').onclick=()=>{checkpoint();strains.forEach((s,i)=>{state.strokes.push({strain:i,member:i%4,size:12,points:Array.from({length:22},(_,j)=>({x:260+i*95,y:200+j*12}))})});refresh();toast('比較五款菌株：切換光線，再播放生長。')};
for(const id of ['place','title','story'])$(id).oninput=()=>state[id]=$(id).value;
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('save').onclick=()=>{download(new Blob([JSON.stringify({version:1,state,light,growth})],{type:'application/json'}),'微生物明信片練習.json');toast('練習檔已下載，請妥善保留。')};$('load').onclick=()=>$('file').click();
$('file').onchange=async()=>{const file=$('file').files[0];if(!file)return;try{if(file.size>10000000)throw Error();const d=JSON.parse(await file.text()),s=d.state;if(d.version!==1||!s||!Array.isArray(s.strokes)||s.strokes.length>10000||!['rect','circle','quad'].includes(s.shape)||!Array.isArray(s.members)||s.members.length!==4||s.members.some(x=>typeof x!=='string'||x.length>30)||['place','title','story'].some(k=>typeof s[k]!=='string'||s[k].length>500))throw Error();for(const t of s.strokes){if(!Number.isInteger(t.strain)||t.strain<0||t.strain>4||!Number.isFinite(t.size)||t.size<3||t.size>24||!Array.isArray(t.points)||t.points.length>100000||t.points.some(p=>!Number.isFinite(p.x)||!Number.isFinite(p.y)||p.x<0||p.x>900||p.y<0||p.y>680))throw Error()}if(state.strokes.length&&!confirm('開啟練習檔將取代目前作品，是否繼續？'))return;stop();state=s;history=[];future=[];growth=Number.isFinite(d.growth)?Math.max(0,Math.min(100,d.growth)):0;light=['day','excite','dark'].includes(d.light)?d.light:'excite';$('growth').value=growth;$('shape').value=s.shape;for(const id of ['place','title','story'])$(id).value=s[id];document.querySelectorAll('#members input').forEach((el,i)=>el.value=s.members[i]);refresh();toast('已載入作品。')}catch{toast('無法開啟：請選擇由本網站儲存的有效練習檔。')}finally{$('file').value=''}};
function wrap(c,text,x,y,width,lineHeight){let line='';for(const char of text){if(char==='\n'||c.measureText(line+char).width>width){c.fillText(line,x,y);line=char==='\n'?'':char;y+=lineHeight}else line+=char}c.fillText(line,x,y);return y+lineHeight}
$('export').onclick=()=>{const out=document.createElement('canvas');out.width=1500;out.height=1050;const c=out.getContext('2d');c.fillStyle='#f0f4ed';c.fillRect(0,0,1500,1050);c.fillStyle='#173c40';c.font='bold 38px sans-serif';c.fillText('微生物明信片',60,75);c.font='18px sans-serif';c.fillText('MICROBIAL POSTCARD · 數位模擬作品',60,110);c.drawImage(canvas,40,160,920,695);c.strokeStyle='#a0b3ad';c.beginPath();c.moveTo(1000,175);c.lineTo(1000,900);c.stroke();c.fillStyle='#173c40';c.font='bold 28px sans-serif';let y=wrap(c,state.title||'未命名作品',1040,210,400,38);c.font='22px sans-serif';y=wrap(c,'寄自：'+(state.place||'尚未填寫'),1040,y+25,400,32);c.font='18px sans-serif';y=wrap(c,state.story||'我們的微生物故事，等待下一筆。',1040,y+22,400,25);c.font='17px sans-serif';wrap(c,'創作者：'+state.members.map((n,i)=>n||`組員 ${i+1}`).join('、'),60,910,1350,25);c.fillText(`觀看模式：${{day:'普通光',excite:'激發光',dark:'黑暗'}[light]}　｜　模擬生長：${growth}%`,60,975);c.font='14px sans-serif';c.fillText('虛擬菌株與示意生長，並非真實培養預測。',60,1010);out.toBlob(b=>{if(b){download(b,'微生物明信片.png');toast('已下載明信片 PNG。')}},'image/png')};
$('help').onclick=()=>$('guide').showModal();$('closeGuide').onclick=()=>$('guide').close();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'get_artwork_summary',description:'Read the current microbial postcard plan and drawing state.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({place:state.place,title:state.title,story:state.story,members:state.members,strokeCount:state.strokes.length,light,growth})})).catch(()=>{})}catch{}}
refresh();
